_target_: src.models.detr_module.DETRModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

args:
  # train
  device: cuda
  lr_backbone: 0.001 # 0 보다 작으면 backbone 학습 안함
  
  # backbone
  backbone: resnet50
  dilation: True
  position_embedding: sine
  
  # Segmentation
  masks: False
  
  # transformer
  enc_layers: 6
  dec_layers: 6
  dim_feedforward: 2048
  hidden_dim: 256
  dropout: 0.1
  nheads: 8
  num_queries: 100
  pre_norm: True
  
  # Loss
  aux_loss: False
  
  # Matcher
  set_cost_class: 1
  set_cost_bbox: 5
  set_cost_giou: 2
  
  # Loss coefficients
  mask_loss_coef: 1
  dice_loss_coef: 1
  bbox_loss_coef: 5
  giou_loss_coef: 2
  eos_coef: 0.1
  
  # dataset parameters
  dataset_file: coco
  